import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar"
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import PlayerControls from "@/components/feature-specific/PlayerControls";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark flex flex-col overflow-hidden`}
      >
        <Navbar />        
        <div className="h-[calc(100vh-168px)] flex">
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 h-[calc(100vh-168px)] py-2 pr-2">
              {children}
            </main>
          </SidebarProvider>
        </div>
        <div className="flex items-center justify-center w-full bg-background h-[100px]" style={{ zIndex: 1000 }}>
          <PlayerControls />
        </div>
      </body>
    </html>
  );
}
